/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IconMdi:reload': typeof import('~icons/mdi/reload')['default']
    'IconUil:alignJustify': typeof import('~icons/uil/align-justify')['default']
    'IconUil:bell': typeof import('~icons/uil/bell')['default']
    'IconUil:check': typeof import('~icons/uil/check')['default']
    'IconUil:cog': typeof import('~icons/uil/cog')['default']
    'IconUil:githubAlt': typeof import('~icons/uil/github-alt')['default']
    'IconUil:linkedinAlt': typeof import('~icons/uil/linkedin-alt')['default']
    'IconUil:trashAlt': typeof import('~icons/uil/trash-alt')['default']
    'IconUil:twitterAlt': typeof import('~icons/uil/twitter-alt')['default']
    'IconUil:user': typeof import('~icons/uil/user')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
