/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'IconMdi:fingerprint': typeof import('~icons/mdi/fingerprint')['default']
    'IconMdi:help': typeof import('~icons/mdi/help')['default']
    'IconMdi:reload': typeof import('~icons/mdi/reload')['default']
    'IconMdi:send': typeof import('~icons/mdi/send')['default']
    'IconMdi:user': typeof import('~icons/mdi/user')['default']
    'IconUil:alignJustify': typeof import('~icons/uil/align-justify')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:bell': typeof import('~icons/uil/bell')['default']
    'IconUil:commentShare': typeof import('~icons/uil/comment-share')['default']
    'IconUil:commentVerify': typeof import('~icons/uil/comment-verify')['default']
    'IconUil:edit': typeof import('~icons/uil/edit')['default']
    'IconUil:exit': typeof import('~icons/uil/exit')['default']
    'IconUil:file': typeof import('~icons/uil/file')['default']
    'IconUil:github': typeof import('~icons/uil/github')['default']
    'IconUil:image': typeof import('~icons/uil/image')['default']
    'IconUil:keySkeleton': typeof import('~icons/uil/key-skeleton')['default']
    'IconUil:linkedin': typeof import('~icons/uil/linkedin')['default']
    'IconUil:message': typeof import('~icons/uil/message')['default']
    'IconUil:plus': typeof import('~icons/uil/plus')['default']
    'IconUil:smile': typeof import('~icons/uil/smile')['default']
    'IconUil:twitter': typeof import('~icons/uil/twitter')['default']
    'IconUil:user': typeof import('~icons/uil/user')['default']
    'IconUil:voicemail': typeof import('~icons/uil/voicemail')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
