// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IconIcRoundMenuOpen: typeof import('~icons/ic/round-menu-open')['default']
    'IconMdi:audio': typeof import('~icons/mdi/audio')['default']
    'IconMdi:chevronDoubleDown': typeof import('~icons/mdi/chevron-double-down')['default']
    'IconMdi:chevronDoubleRight': typeof import('~icons/mdi/chevron-double-right')['default']
    'IconMdi:file': typeof import('~icons/mdi/file')['default']
    'IconMdi:image': typeof import('~icons/mdi/image')['default']
    'IconMdi:reload': typeof import('~icons/mdi/reload')['default']
    'IconMdi:send': typeof import('~icons/mdi/send')['default']
    'IconMdi:user': typeof import('~icons/mdi/user')['default']
    'IconMdi:vice': typeof import('~icons/mdi/vice')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:commentShare': typeof import('~icons/uil/comment-share')['default']
    'IconUil:dashboard': typeof import('~icons/uil/dashboard')['default']
    'IconUil:edit': typeof import('~icons/uil/edit')['default']
    'IconUil:enter': typeof import('~icons/uil/enter')['default']
    'IconUil:exit': typeof import('~icons/uil/exit')['default']
    'IconUil:face': typeof import('~icons/uil/face')['default']
    'IconUil:github': typeof import('~icons/uil/github')['default']
    'IconUil:home': typeof import('~icons/uil/home')['default']
    'IconUil:linkedin': typeof import('~icons/uil/linkedin')['default']
    'IconUil:smile': typeof import('~icons/uil/smile')['default']
    'IconUil:tweeter': typeof import('~icons/uil/tweeter')['default']
    'IconUil:twitter': typeof import('~icons/uil/twitter')['default']
    'IconUil:voicemail': typeof import('~icons/uil/voicemail')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
