# backend:
#   name: proxy
#   proxy_url: http://localhost:8081/api/v1
#   branch: master # optional, defaults to master

backend:
  name: github
  repo: mehotkhan/front
  base_url: https://alizemani.ir
  auth_endpoint: /auth

media_folder: /public/content
public_folder: /content
collections:
  - name: "notes"
    label: "یادداشت"
    folder: "content/notes"
    create: true
    slug: "{{url}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "آدرس", name: "url", widget: "string" }
      - { label: "جهت نوشتار", name: "dir", widget: "string" }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }

      - name: category
        label: سرویس
        widget: relation
        collection: "category"
        searchFields: ["name"]
        valueField: "name"
        displayFields: ["name"]

      - { label: "برچسب‌ها", name: "tags", widget: "list" }
      - { label: "پوستر", name: "thumbnail", widget: "image" }
      - { label: "خلاصه", name: "description", widget: "string" }
      - { label: "محتوا", name: "body", widget: "markdown" }

  - name: "page"
    label: "صفحه"
    folder: "content/pages"
    create: false
    slug: "{{url}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "آدرس", name: "url", widget: "string" }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }
      - { label: "محتوا", name: "body", widget: "markdown" }

  - name: "banner"
    label: "بنر"
    folder: "content/banner"
    create: true
    slug: "{{url}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "آدرس", name: "url", widget: "string" }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }
      - { label: "پوستر", name: "thumbnail", widget: "image" }
      - { label: "محتوا", name: "body", widget: "markdown" }

  - name: category
    label: سرویس‌ها
    folder: content/categories/
    create: true
    slug: "{{url}}"
    identifier_field: name
    fields:
      - { name: name, label: نام }
      - { name: url, label: آدرس }
