backend:
  name: github
  repo: mehotkhan/front
  base_url: https://alizemani.ir
  auth_endpoint: /auth
media_folder: /public/content
public_folder: /content
collections:
  - name: "notes"
    label: "یادداشت ها"
    folder: "content/notes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }
      - { label: "پوستر", name: "thumbnail", widget: "image" }
      - { label: "خلاصه", name: "description", widget: "string" }
      - { label: "محتوا", name: "body", widget: "markdown" }

  - name: "page"
    label: "صفحه ها"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }
      - { label: "محتوا", name: "body", widget: "markdown" }